### ISSUE TITLE
Wrong newsfeed link.

### ISSUE THREAD

**Issue by Dhruvi16** [creativecommons/creativecommons.github.io-source#475] opened 2020-08-24 10:23 UTC
## Description

The newsfeed link on the blog page takes the user to some XML file which is not expected.

## Reproduction

1. Go to [Blog page](https://opensource.creativecommons.org/blog/entries/)
2. Click on `news feed here`
3. See error.

## Expectation

It should take the user to a legitimate news feed subscription page.

## Environment

 - Device:laptop
 - OS: Ubuntu 16.04
 - Browser:  Firefox
 - Version: 75

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by Dhruvi16** [comment] 2020-08-24 10:23
I am not sure about where this link should take the user.

**Comment by kgodey** [comment] 2020-08-24 13:53
@Dhruvi16 this is not a bug, if you put that URL into your RSS reader, it will subscribe to it.

What kind of page where you expecting?

**Comment by dhruvkb** [comment] 2020-08-24 14:06
I think if we change the text to "RSS feed" and/or put the [RSS icon](https://en.wikipedia.org/wiki/RSS#/media/File:Feed-icon.svg) alongside it, it would make it quite clear.

**Comment by kgodey** [comment] 2020-08-24 14:13
I'm in support of doing both those things.

**Comment by Dhruvi16** [comment] 2020-08-24 14:42
Oh! I got confused. I agree with @dhruvkb here.

**Comment by kgodey** [comment] 2020-08-24 14:53
go ahead! do we have an RSS icon in Vocabulary?

**Comment by zackkrida** [comment] 2020-08-24 14:57
There is not an RSS icon.

**Comment by Dhruvi16** [comment] 2020-08-24 15:14
I will add an issue and make a PR to add an RSS icon. Is that okay @zackkrida?

**Comment by kgodey** [comment] 2020-09-25 16:14
@Dhruvi16 is this ready for work now that the icon is in Vocabulary?

**Comment by Dhruvi16** [comment] 2020-09-26 16:22
On it.

**Comment by Dhruvi16** [comment] 2020-09-26 16:51
I guess these icons will be available in the next release right? @zackkrida

**Comment by zackkrida** [comment] 2020-09-26 18:44
@Dhruvi16 they should be available now, let me check if something went wrong with the build on the latest version!

**Comment by zackkrida** [comment] 2020-09-26 19:45
@Dhruvi16 yes the `rss-square` icon is available in the latest vocabulary. The fonts storybook just hadn't updated. I did vue and vocab but forgot that one. It's fixed now:

https://cc-fonts.netlify.app/?path=/docs/vocabulary-icons--page

**Closed** 2020-10-05 23:23 UTC
Labels: 🛠 goal: fix
