### ISSUE TITLE
Relative path error with page links when in development

### ISSUE THREAD

**Issue by sp35** [creativecommons/creativecommons.github.io-source#303] opened 2020-06-16 09:29 UTC
## Description

Relative path error when in development. 
My branch is up to date with `creativecommons.github.io-source master`. There isn't such an issue on the live site, hence the mention of _development_.

## Reproduction

1. Go to the index page
2. Try clicking `All our projects` in the `Integrate with CC Tools` card.
3. Notice the URL on your browser if a 404

## Expectation

Relative path should work correctly as intended.

## Screenshots

![Screenshot from 2020-06-16 14-56-42](https://user-images.githubusercontent.com/51958314/84757400-b953ca00-afe1-11ea-9cab-54280edd25ba.png)
![Screenshot from 2020-06-16 14-56-46](https://user-images.githubusercontent.com/51958314/84757410-bbb62400-afe1-11ea-859c-b0a7972ce67e.png)

## Environment

 - Device: laptop
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 83.0.4103.61 (Official Build) (64-bit)
 - Other info: 1366x768 (16:9)

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by NealldeWaal** [comment] 2020-06-21 05:01
I would be interested in resolving this bug.

**Comment by sp35** [comment] 2020-06-21 05:03
Great, go ahead @NealldeWaal!

**Comment by Rudresh22** [comment] 2020-06-30 05:01
@NealldeWaal are you working on this issue? If not please inform as I am interested in working on it.

**Comment by NealldeWaal** [comment] 2020-06-30 12:14
@Rudresh22 please take over. Ran into unrelated issues.

**Comment by ritesh-pandey** [comment] 2020-07-12 14:23
@Rudresh22 Are you working on this? If not, I would like to take this up.

**Comment by Rudresh22** [comment] 2020-07-13 04:41
@ritesh-pandey Go ahead, you can take it over.

**Comment by kgodey** [comment] 2020-07-16 15:44
The issue is fixed for the links @sp35 identified, but there are more errors all over the site e.g. the links to "Project Roles" and "Community building roles" on the Community Team page. It looks like they all need a trailing slash.

I'll leave this issue open, please feel free to submit PRs fixing individual pages/links, they don't all have to be done at once.

**Comment by Rudresh22** [comment] 2020-07-16 16:02
Hey @kgodey , the links to "Project Roles" and "Community building roles" seem to be working when I visited the community team page.

**Comment by ritesh-pandey** [comment] 2020-07-16 16:50
https://github.com/creativecommons/creativecommons.github.io-source/pull/337#issuecomment-659536585

**Closed** 2020-07-20 16:52 UTC
Labels: bug, good first issue, help wanted
